title: Conrad Li
subtitle: Software Engineer II
description: 
avatar:

default_theme: "dark"

about: 
  "I am a software engineer at Bank of America in New York, NY. I graduated in 2021 from Bowdoin College with a major in Computer Science and a minor in Sociology (and Economics, informally). I am interested in the intersection between tech and education, specifically providing opportunities for first-gen college students like myself. 

  <br><br>

  For summer 2020, I was a Global Tech Analyst at Bank of America where my team delivered the top three time series prediction models for daily ATM volume estimations out of all intern groups.

  <br><br>
  
  <b>At this time, I am not looking for a job, but I am open to new opportunities! I am interested in exploring product management and software engineer.</b> I have experience with Python, Java, C++, Kotlin, HTML, CSS/SASS, JS, machine learning models, agile development, and a willingness to learn."

defaults:
  -
    scope:
      path: "/_posts/"
    values:
      layout: "post"

collections:
  pages:
    output: true
    permalink: /:title/
  
  posts:
    output: true
    permalink: /blog/:title/
    category: /blog/

  photography:
    output: true
    permalink: /photography/:title/
    category: /photography/
  
  portfolio:
    output: true
    permalink: /portfolio/:title/
    category: /portfolio/


# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Blog
    link: /blog/
    icon: ""
    
  #- text: Portfolio
  #  link: /portfolio/
  #  icon: ""
  
  - text: Photography
    link: /photography/
    icon: ""

  - text: Resume
    link: /resume/
    icon: ""

 # - text: Contact
 #   link: /contact/
 #   icon: ""
  



# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/conrad-li/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/conrad-li
    icon: fab fa-github-square





###########################
##### Resume settings #####
###########################
resume_name:                    "Conrad Li"
resume_title:                   ""
resume_contact_email:           "conradzli@hotmail.com"
resume_contact_telephone:       ""
resume_contact_address:         ""
resume_header_contact_info:     "No address at the moment • conradzli@hotmail.com"
display_header_contact_info:    "false"



# Display resume sections
resume_section_education:       true
resume_section_skills:          true
resume_section_experience:      true
resume_section_projects:        true
resume_section_associations:    true
resume_section_interests:       true


# Resume social links
resume_social_links:
  resume_github_url:             "https://github.com/conrad-li"
  #resume_twitter_url:           
  #resume_facebook_url:         
  resume_linkedin_url:           "https://www.linkedin.com/in/conrad-li/"
  #resume_instagram_url:         
  resume_website_url:            "https://conrad-li.github.io/conradli"
  #resume_medium_url:
resume_print_social_links:       true


# plugin 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# sass 
sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown